services:
  - type: web
    name: vapi-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn vapi_service:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: VAPI_PRIVATE_KEY
        sync: false