services:
  - type: web
    name: ctc-vapi-backend
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements-backend.txt"
    startCommand: "cd backend && uvicorn vapi_service:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: VAPI_PRIVATE_KEY
        sync: false
    healthCheckPath: /health